env: "gymma"

env_args:
  key: null
  time_limit: 1000
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 500000
log_interval: 500000
runner_log_interval: 500000
learner_log_interval: 500000
t_max: 4000000


